[kube-prometheus-stack] Fix cascade parameter
According to documentation when trying to use cascade=orphan

Error: invalid argument "orphan" for "--cascade" flag: strconv.ParseBool: parsing "orphan": invalid syntax

using true instead of orphan fixes this